// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemamusicafinal.Models;

#nullable disable

namespace sistemamusicafinal.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sistemamusicafinal.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdAlbum");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantorId")
                        .HasColumnType("int");

                    b.Property<byte[]>("CapaAlbum")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("CapaAlbum");

                    b.Property<string>("GeneroAlbum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GeneroAlbum");

                    b.Property<string>("TituloAlbum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TituloAlbum");

                    b.HasKey("Id");

                    b.HasIndex("CantorId");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("sistemamusicafinal.Models.Cantor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCantor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GeneroCantor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GeneroCantor");

                    b.Property<string>("NomeCantor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeCantor");

                    b.HasKey("Id");

                    b.ToTable("Cantor");
                });

            modelBuilder.Entity("sistemamusicafinal.Models.Musica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMusica");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("DuracaoMusica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuracaoMusica");

                    b.Property<string>("TituloMusica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TituloMusica");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Musica");
                });

            modelBuilder.Entity("sistemamusicafinal.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailUsuario");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeUsuario");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SenhaUsuario");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("sistemamusicafinal.Models.Album", b =>
                {
                    b.HasOne("sistemamusicafinal.Models.Cantor", "Cantor")
                        .WithMany()
                        .HasForeignKey("CantorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cantor");
                });

            modelBuilder.Entity("sistemamusicafinal.Models.Musica", b =>
                {
                    b.HasOne("sistemamusicafinal.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });
#pragma warning restore 612, 618
        }
    }
}
